package me.antcode.TypesOfAction;

/**
 * Individual plays
 */
public enum Actions {

    LOST_BALL("Lost Ball Turnover"),
    BAD_PASS("bad pass"),
    OUT_OF_BOUNDS_BAD_PASS("Out of Bounds - Bad Pass Turnover"),
    OUT_OF_BOUNDS_LOST_BALL("Out of Bounds - Lost Ball Turnover"),
    OUT_OF_BOUNDS_STEP("Out of Bounds - Step Turnover"),
    OFFENSIVE_FOUL_TURNOVER("Offensive Foul Turnover"),
    DEFENSIVE_FOUL_TURNOVER("Defensive Foul Turnover"),
    SHOT_CLOCK_TURNOVER("Shot Clock Turnover"),
    DRIVING_DUNK_SHOT("Driving Dunk Shot"),
    JUMP_SHOT("Jump Shot"),
    PULL_UP_JUMP_SHOT("Pullup Jump Shot"),
    FADE_AWAY_JUMP_SHOT("Fade Away Jump Shot"),
    FADE_AWAY_BANK_JUMP_SHOT("Fade Away Bank Jump Shot"),
    TURNAROUND_HOOK_SHOT("Turnaround Hook Shot"),
    REF_REVIEW("REF-INITIATED REVIEW"),
    CUTTING_FINGER_ROLL_LAYUP_SHOT("Cutting Finger Roll Layup Shot"),
    RUNNING_ALLEY_OOP_DUNK_SHOT("Running Alley Oop Dunk Shot"),
    REVERSE_DUNK_SHOT("Reverse Dunk Shot"),
    TURNAROUND_BANK_JUMP_SHOT("Turnaround Bank Jump Shot"),
    TIP_SHOT("Tip Shot"),
    RUNNING_DUNK_SHOT("Running Dunk Shot"),
    LAYUP_SHOT("Layup Shot"),
    DRIVING_FLOATING_JUMP_SHOT("Driving Floating Jump Shot"),
    REVERSE_LAYUP_SHOT("Reverse Layup Shot"),
    STEP_BACK_JUMP_SHOT("Step Back Jump Shot"),
    RUNNING_LAYUP_SHOT("Running Layup Shot"),
    DRIVING_LAYUP_SHOT("Driving Layup Shot"),
    TURNAROUND_FADE_AWAY_BANK_JUMP_SHOT("Turnaround Fadeaway Bank Jump Shot"),
    TURNAROUND_FADE_AWAY_JUMP_SHOT("Turnaround Fade Away Jump Shot"),
    RUNNING_JUMP_SHOT("Running Jump Shot"),
    RUNNING_FINGER_ROLL_LAYUP("Running Finger Roll Layup"),
    UNAVAILABLE("Not Available"),
    KICKED_BALL("Kicked Ball"),
    FINGER_ROLL_LAYUP("Finger Roll Layup"),
    HOOK_SHOT("Hook Shot"),
    DRIVING_HOOK_SHOT("Driving Hook Shot"),
    CUTTING_LAYUP_SHOT("Cutting Layup Shot"),
    TURNAROUND_JUMP_SHOT("Turnaround Jump Shot"),
    DUNK_SHOT("Dunk Shot"),
    LAYUP_RUNNING_REVERSE("Layup Running Reverse"),
    DRIVING_FINGER_ROLL_LAYUP("Driving Finger Roll Layup"),
    PUTBACK_DUNK_SHOT("Putback Dunk Shot"),
    DRIVING_FLOATING_BANK_JUMP_SHOT("Driving Floating Bank Jump Shot"),
    RUNNING_PULLUP_JUMP_SHOT("Running Pullup Jump Shot"),
    CUTTING_DUNK_SHOT("Cutting Dunk Shot"),
    HOOK_TURNAROUND_BANK("Hook Turnaround Bank"),
    PULLUP_BANK_JUMP_SHOT("Pullup Bank Jump Shot"),
    ALLEY_OOP_DUNK_SHOT("Alley Oop Dunk Shot"),
    ALLEY_OOP_LAYUP_SHOT("Alley Oop Layup Shot"),
    LAYUP_DRIVING_REVERSE("Layup Driving Reverse"),
    FLOATING_JUMP_SHOT("Floating Jump Shot"),
    JUMP_SHOT_BANK("jump bank shot"),
    LAYUP_SHOT_PUTBACK("Layup Shot Putback"),
    HOOK_DRIVING_BANK("Hook Driving Bank"),
    JUMP_BALL("Jumpball"),
    OFFENSIVE_REBOUND("Offensive Rebound"),
    DEFENSIVE_REBOUND("Defensive Rebound"),
    OFFENSIVE_TEAM_REBOUND("Offensive Team Rebound"),
    DEFENSIVE_TEAM_REBOUND("Defensive Team Rebound"),
    TIP_DUNK_SHOT("Tip Dunk Shot"),
    TRAVELING("Traveling"),
    SHOOTING_FOUL("Shooting Foul"),
    LOOSE_BALL_FOUL("Loose Ball Foul"),
    PERSONAL_FOUL("Personal Foul"),
    TECHNICAL_FOUL("Technical Foul"),
    DOUBLE_TECHNICAL_FOUL("Double Technical Foul"),
    PERSONAL_TAKE_FOUL("Personal Take Foul"),
    OFFENSIVE_FOUL("Offensive Foul"),
    DEFENSIVE_FOUL("Defensive Foul"),
    DEFENSIVE_THREE_SECONDS_TECH("Defensive 3-Seconds Technical"),
    FLAGRANT_FOUL_TYPE_ONE("Flagrant Foul Type 1"),
    INTENTIONAL_FOUL("Intentional Foul"),
    OFFENSIVE_CHARGE("Offensive Charge"),
    DEFENSIVE_CHARGE("Defensive Charge"),
    DEFENSIVE_GOALTENDING("Defensive Goaltending"),
    OFFENSIVE_GOALTENDING("Offensive Goaltending"),
    TRANSITION_TAKE_FOUL("Transition Take Foul"),
    BLOCK("blocks"),
    LANE_VIOLATION("Lane"),
    CHALLENGE("Challenge"),
    BLOCK_OFFENSIVE_REBOUND("Block To Offensive Rebound"),
    BLOCK_DEFENSIVE_REBOUND("Block to Defensive Rebound"),
    SUBSTITUTION("Substitution"),
    END_PERIOD("End Period"),
    END_GAME("End Game"),
    FREE_THROW_ONE_OF_TWO("Free Throw - 1 of 2"),
    FREE_THROW_TWO_OF_TWO("Free Throw - 2 of 2"),
    FREE_THROW_ONE_OF_THREE("Free Throw - 1 of 3"),
    FREE_THROW_TWO_OF_THREE("Free Throw - 2 of 3"),
    FREE_THROW_THREE_OF_THREE("Free Throw - 3 of 3"),
    FREE_THROW_TECH("Free Throw - Technical"),
    FREE_THROW_ONE_OF_ONE("Free Throw - 1 of 1"),
    FREE_THROW_FLAGRANT_ONE_OF_TWO("Free Throw - Flagrant 1 of 2"),
    FREE_THROW_FLAGRANT_TWO_OF_TWO("Free Throw - Flagrant 2 of 2"),
    COACHCHALLENGE("COACH'S CHALLENGE"),
    TIMEOUT("timeout"),
    UNIDENTIFIED("This action was not picked up");

    private final String description;

    Actions(String description){
        this.description = description;
    }

    public String getDescription() {
        return description;
    }
}
