package me.antcode.plays;

/**
 * All different types of plays combined
 */
public enum PlayTypes {

    BLOCK_AND_POSSESSION_CHANGE,
    BLOCK_AND_NO_POSSESSION_CHANGE,
    MADE_SHOT,
    ASSIST_MADE_SHOT,
    MISSED_SHOT,
    MISSED_SHOT_OFFENSIVE_REBOUND_TEAM,
    MISSED_SHOT_DEFENSIVE_REBOUND_TEAM,
    MISSED_SHOT_OFFENSIVE_REBOUND,
    MISSED_SHOT_DEFENSIVE_REBOUND,
    FOUL,
    FLAGRANT_FOUL_TYPE_ONE,
    FLAGRANT_FOUL_TYPE_TWO,
    OFFENSIVE_REBOUND_TEAM,
    DEFENSIVE_REBOUND_TEAM,
    OFFENSIVE_REBOUND,
    DEFENSIVE_REBOUND,
    DOUBLE_TECHNICAL_FOUL,
    TECHNICAL_FOUL,
    PERSONAL_TAKE_FOUL,
    TRANSITION_TAKE_FOUL,
    DEFENSIVE_THREE_SECONDS_FOUL,
    PERSONAL_FOUL,
    SHOOTING_FOUL,
    LOOSE_BALL_FOUL,
    OFFENSIVE_FOUL,
    REBOUND,
    FREE_THROW,
    FREE_THROW_TECHNICAL,
    FREE_THROW_DEFENSIVE_REBOUND,
    FREE_THROW_OFFENSIVE_REBOUND,
    FREE_THROW_DEFENSIVE_REBOUND_TEAM,
    FREE_THROW_OFFENSIVE_REBOUND_TEAM,
    SUBSTITUTION,
    TURNOVER,

    SHOT_CLOCK_TURNOVER,
    DOUBLE_DRIBBLE_TURNOVER,
    BAD_PASS_TURNOVER,
    TRAVELING_TURNOVER,
    LOST_BALL_TURNOVER,
    OUT_OF_BOUNCE_TURNOVER,
    STEAL_TURNOVER,
    OFFENSIVE_FOUL_TURNOVER,

    JUMPBALL,
    VIOLATION,
    FREE_THROW_FLAGRANT,
    UNIDENTIFIEDPLAYTYPE,
    TIMEOUT;

}
