package me.antcode.plays;

/**
 * All different types of plays combined
 */
public enum PlayTypes {

    BLOCK_AND_POSSESSION_CHANGE,
    BLOCK_AND_NO_POSSESSION_CHANGE,
    MADE_SHOT,
    MADE_SHOT_FOUL,
    ASSIST_MADE_SHOT,
    ASSIST_MADE_SHOT_FOUL,
    MISSED_SHOT,
    MISSED_SHOT_FOUL,
    MISSED_SHOT_OFFENSIVE_REBOUND,
    MISSED_SHOT_OFFENSIVE_REBOUND_FOUL,
    MISSED_SHOT_DEFENSIVE_REBOUND,
    MISSED_SHOT_DEFENSIVE_REBOUND_FOUL,
    FO_FREE_THROW_MAKE,
    FOUL_FREE_THROW_MISS,
    FOUL_FREE_THROW_MAKE_FREE_THROW_MISS,
    FOUL_FREE_THROW_MAKE_FREE_THROW_MAKE,
    FOUL_FREE_THROW_MISS_FREE_THROW_MISS,
    FREE_THROW,
    SUBSTITUTION,
    BAD_PASS_TURNOVER,
    TURNOVER_FOUL,
    SHOOTING_FOUL,
    LOOSE_BALL_FOUL,
    REBOUND,
    TURNOVER,
    JUMPBALL,
    UNIDENTIFIEDPLAYTYPE


}
